### ISSUE TITLE
Support for androidx

### ISSUE THREAD

**Issue by KartikShankhavaram** [wasabeef/recyclerview-animators#162]
Hey, is it possible to get support for androidx for this library? The current version builds just fine but it shows errors in Android Studio since the classes are basically the same but the package names are not.

**Comment by BreSmit521** [comment]
Any update on this ticket?

**Comment by wasabeef** [comment]
@KartikShankhavaram @BreSmit521 

Just migrate to AndroidX #165

**Comment by kingargyle** [comment]
If you are migrating to AndroidX, I would HIGHLY recommend a major version bump.   There are numerous problems people are having trying to use a mixed AndroidX and support library installation, and forcing users to migrate to AndroidX in order to use the new versions.  This is a breaking change for many so should require a new major version update.
